name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        architecture: [x64, arm64]
        toolchain: 
          - 1.75.0
        exclude:
          - os: macos-latest
            architecture: x64

    steps:
      - uses: actions/checkout@v4
      - run: >-
          rustup toolchain install ${{matrix.toolchain }} &&
          rustup component add rustfmt --toolchain ${{matrix.toolchain }} &&
          rustup component add clippy --toolchain ${{matrix.toolchain }} &&
          rustup default ${{matrix.toolchain }}

      - name: Check for Format Errors
        run: cargo fmt -- --check

      - name: Run Clippy
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
